language: php
cache:
  directories:
    - vendor
    - $HOME/.composer/cache
    - $HOME/.php-cs-fixer

branches:
  except:
    - /\+travis\d+$/

php:
  - 7.4

matrix:
  fast_finish: true

install:
  - yes | pecl install imagick
  - composer install --no-interaction

script:
  # Check against CRLF
  - scripts/check-crlf.sh
  # Check against trailing whitespaces on php files
  - scripts/check-trailling-spaces.sh .
  # Check against non utf-8 files
  - scripts/check-utf8.sh .
  # Check php syntax
  - scripts/phplint.sh ./downloader/
  - scripts/phplint.sh ./uploader/
  # Check CS fixer
  - vendor/bin/php-cs-fixer --no-interaction --dry-run --diff -v fix
