name: Docker build
inputs:
  dockerhub_username:
    description: docker hub username
    type: string
  dockerhub_token:
    description: docker hub token
    type: string

runs:
  using: "composite"
  steps:
    - name: base
      uses: geokrety/geokrety-gha-workflows/.github/actions/docker-build@main
      id: docker-base
      with:
        image_name: geokrety/pictures-processor-base
        dockerhub_username: ${{ inputs.dockerhub_username }}
        dockerhub_token: ${{ inputs.dockerhub_token }}
        dockerfile: Dockerfile.base

    - name: Debug
      uses: raven-actions/debug@v1

    - name: uploader
      uses: geokrety/geokrety-gha-workflows/.github/actions/docker-build@main
      id: docker-uploader
      with:
        image_name: geokrety/pictures-processor-uploader
        dockerhub_username: "${{ inputs.dockerhub_username }}"
        dockerhub_token: "${{ inputs.dockerhub_token }}"
        dockerfile: Dockerfile.uploader
        build_args: BASE_TAG=${{ env.DOCKER_METADATA_OUTPUT_VERSION }}

    - name: downloader
      uses: geokrety/geokrety-gha-workflows/.github/actions/docker-build@main
      id: docker-downloader
      with:
        image_name: geokrety/pictures-processor-downloader
        dockerhub_username: ${{ inputs.dockerhub_username }}
        dockerhub_token: ${{ inputs.dockerhub_token }}
        dockerfile: Dockerfile.downloader
        build_args: BASE_TAG=${{ env.DOCKER_METADATA_OUTPUT_VERSION }}
