name: docker-build

on:
  schedule:
    - cron: "0 10 * * *"
  push:
    branches:
      - "!main"
    tags:
      - "v*.*.*"
  pull_request:
  workflow_call:
    inputs:
      dockerhub_username:
        required: true
        type: string
    secrets:
      dockerhub_token:
        required: true

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: ./.github/actions/docker-build
        with:
          dockerhub_username: ${{ inputs.dockerhub_username }}
          dockerhub_token: ${{ secrets.dockerhub_token }}
