name: docker-build

on:
  push:
    tags:
      - '*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set output
        id: vars
        run: |
          echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}

          raw=$(git branch -r --contains ${{ github.ref }})
          branch=${raw/origin\/}
          echo ::set-env name=BRANCH::$branch

      - name: Build and push - base
        uses: docker/build-push-action@v4
        with:
          file: Dockerfile.base
          push: true
          tags: geokrety/pictures-processor-base:${{ steps.vars.outputs.BRANCH }},geokrety/pictures-processor-base:${{ steps.vars.outputs.short_ref }}

      - name: Build and push - downloader
        uses: docker/build-push-action@v4
        with:
          file: Dockerfile.downloader
          push: true
          build-args: |
            BASE_TAG=${{ steps.vars.outputs.short_ref }}
          tags: geokrety/pictures-processor-downloader:${{ steps.vars.outputs.BRANCH }},geokrety/pictures-processor-downloader:${{ steps.vars.outputs.short_ref }}

      - name: Build and push - uploader
        uses: docker/build-push-action@v4
        with:
          file: Dockerfile.uploader
          push: true
          build-args: |
            BASE_TAG=${{ steps.vars.outputs.short_ref }}
          tags: geokrety/pictures-processor-uploader:${{ steps.vars.outputs.BRANCH }},geokrety/pictures-processor-uploader:${{ steps.vars.outputs.short_ref }}
