name: docker-build

on:
  schedule:
    - cron: "0 10 * * *"
  push:
    branches-ignore:
      - main
    tags:
      - "v*.*.*"
  pull_request:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/docker-build
        with:
          dockerhub_username: "${{ vars.DOCKERHUB_USERNAME }}"
          dockerhub_token: "${{ secrets.DOCKERHUB_TOKEN }}"
