name: docker-build

on:
  schedule:
    - cron: "0 10 * * *"
  push:
    branches:
      - "**"
    tags:
      - "v*.*.*"
  pull_request:

jobs:
  docker-base:
    uses: geokrety/geokrety-gha-workflows/.github/workflows/docker-build.yml@main
    with:
      image_name: geokrety/pictures-processor-base
      dockerhub_username: ${{ vars.DOCKERHUB_USERNAME }}
      dockerfile: Dockerfile.base
    secrets:
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}

  docker-uploader:
    uses: geokrety/geokrety-gha-workflows/.github/workflows/docker-build.yml@main
    needs: docker-base
    with:
      image_name: geokrety/pictures-processor-uploader
      dockerhub_username: ${{ vars.DOCKERHUB_USERNAME }}
      dockerfile: Dockerfile.uploader
    secrets:
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}

  docker-downloader:
    uses: geokrety/geokrety-gha-workflows/.github/workflows/docker-build.yml@main
    needs: docker-base
    with:
      image_name: geokrety/pictures-processor-downloader
      dockerhub_username: ${{ vars.DOCKERHUB_USERNAME }}
      dockerfile: Dockerfile.downloader
    secrets:
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
