name: docker-build

on:
  push:
    tags:
      - '*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push - base
        uses: docker/build-push-action@v4
        with:
          file: Dockerfile.base
          push: true
          tags: geokrety/pictures-processor-base:latest

      - name: Build and push - downloader
        uses: docker/build-push-action@v4
        with:
          file: Dockerfile.downloader
          push: true
          tags: geokrety/pictures-processor-downloader:latest

      - name: Build and push - uploader
        uses: docker/build-push-action@v4
        with:
          file: Dockerfile.uploader
          push: true
          tags: geokrety/pictures-processor-uploader:latest
