name: docker-build

on:
  push:
    branches-ignore:
      - main
    tags:
      - "v*.*.*"
  pull_request:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/docker-build
        with:
          dockerhub_username: "${{ vars.DOCKERHUB_USERNAME }}"
          dockerhub_token: "${{ secrets.DOCKERHUB_TOKEN }}"

  update-version-set:
    uses: geokrety/geokrety-gha-workflows/.github/workflows/version-set.yml@main
    needs: docker
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

  deploy:
    uses: geokrety/geokrety-gha-workflows/.github/workflows/trigger-staging-deploy.yml@main
    needs: docker
    secrets:
      DEPLOY_HEADER_NAME: ${{ secrets.DEPLOY_HEADER_NAME }}
      DEPLOY_HEADER_VALUE: ${{ secrets.DEPLOY_HEADER_VALUE }}
      DEPLOY_URL: ${{ secrets.DEPLOY_URL }}
